import {
  Card,
  CardContent,
  CardHeader,
  Container,
  Divider,
  Grid,
  Paper,
  Typography,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/Header";

function FeatGridCard(props: { title: string; children: string }) {
  const { title, children } = props;
  return (
    <Grid item xs={4}>
      <Card sx={{ height: "100%" }}>
        <CardHeader title={title} />
        <CardContent>{children}</CardContent>
      </Card>
    </Grid>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bancuh DNS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container maxWidth="lg">
        <Header />
        <Paper
          sx={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            paddingY: 20,
            marginY: 10,
          }}
        >
          <Typography variant="h2" gutterBottom>
            Free Adblock DNS
          </Typography>

          <Typography variant="overline" gutterBottom sx={{ fontSize: 20 }}>
            Block ads on you entire wifi network, laptop, PC, tablets and
            phones.
          </Typography>
        </Paper>
        <Divider />

        <Grid container spacing={6}>
          <FeatGridCard title="Safe and Ad-free browsing experience">
            Browse the web, without any intrusive ads or tracking services.
            Known malware sites are also blocked to further protect your
            experience.
          </FeatGridCard>

          <FeatGridCard title="Family-Safe browsing">
            Block sites with adult contents. Keep your family browsing
            experience safe.
          </FeatGridCard>

          <FeatGridCard title="Zero Cost & Completely FREE">
            This service will remain free for as long as possible.
          </FeatGridCard>

          <FeatGridCard title="Minimal Setup">
            Zero installation. Point your network to our DNS servers, and you
            are done. Visit the Quick Start link to set up Adblock DNS on your
            network.
          </FeatGridCard>

          <FeatGridCard title="Fast performance & low impact">
            Blocking ads removes the unwanted Internet traffic from your
            network. Blocking ads also reduces the processing load on your
            computer. With Adblocking done at the DNS level, there is no
            performance impact on your device. No browser extensions or plugins
            need to run on your computer.
          </FeatGridCard>

          <FeatGridCard title="Always updated">
            Are you tired of constantly having to update your hosts file, every
            time a new adserver pops up? We keep our servers updated, so you can
            keep browsing worry-free. We also leverage public adblock lists
            maintained by the wide adblocking community, and our servers refresh
            constantly as the upstream lists update.
          </FeatGridCard>

          <FeatGridCard title="Open Source FTW!!">
            Bancuh DNS is powered by open sourced tools and software. All the
            custom codes, scripts, and adblock lis sources that we use are
            public and on GitHub. We continue to enhance and improve the project
            based on community feedback, and all work is done in the open.
          </FeatGridCard>
        </Grid>
      </Container>
    </>
  );
};

export default Home;
